#!/bin/sh
# Copyright(c) 2016 Jonathan Poland
DIR="/usr/syno/synoman/webman/3rdparty/Medio"
if [ "$SYNOPKG_PKG_STATUS" = "UNINSTALL" ]; then
	echo "Thanks for trying Medio, sorry to see you go.  Feedback is appreciated!  https://bitbucket.org/polandj/medio/" >> $SYNOPKG_TEMP_LOGFILE
fi
rm -f $DIR
exit 0
