#!/bin/sh
# Copyright(c) 2016 Jonathan Poland

PID=""
get_pid() 
{
    PID=`ps -w | grep -v grep | grep python | grep medio | awk '{print $1}'`
}
case $1 in
	start)
		python ${SYNOPKG_PKGDEST}/medio.py & 
		exit 0
	;;
	stop)
		get_pid
		if [ ! -z $PID ]; then
			kill $PID
		fi
		exit 0
	;;
	status)
		get_pid
		if [ -z $PID ]; then
			exit 1
		else
			exit 0	
                fi
	;;
	log)
		echo "${SYNOPKG_PKGDEST}/medio.log"
		exit 0
	;;
esac
                                     
